apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rsweb1
spec:
  replicas: 1
  selector:
    matchLabels:
      env: dev
    matchExpressions:
     - { key: env, operator: In, values: [ dev ] }
  template:
    metadata:
      name: mypod1
      labels:
        env: dev
    spec:
      containers:
      - name: "mycon1"
        image: "vimal13/apache-webserver-php"
        volumeMounts:
         - name: web-vol1
           mountPath:  /var/www/html
      volumes:
       - name: web-vol1 
         persistentVolumeClaim: 
           claimName: mypvc1

apiVersion: v1
kind: Service
metadata:
  name: myinternallb
spec:
  selector:
    env: dev
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
